spring:
  profiles:
    active: dev

---
# Puerto de entorno de desarrollo generado por Eureka
server:
  port: 8011
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://serveo.net:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-same-zone-eureka: false

resilience4j:
  circuitbreaker:
    instances:
      myCircuitBreaker:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 60000
        automatic-transition-from-open-to-half-open-enabled: true
  timelimiter:
    instances:
      myTimeLimiter:
        timeout-duration: 1s

management:
  endpoints:
    web:
      exposure:
        include:
            - mappings
            - env
            - health
            - info
            - hystrix.stream
#      base-path: /actuator
#      cors:
#        allowed-origins: true
#  endpoint:
#    health:
#      enabled: true
#      show-details: always
  info:
    env:
      enabled: true
  health:
    enabled: true
    show-details: always

info:
  app:
    version: 1.0.0
    name: Microservices HelloWorld
    description: Microservices to test Zipkin

spring:
  application:
    zipkin: http://localhost:9411

message: "hola mundo!!"