spring:
  profiles:
    active: dev
---
# Puerto de entorno de desarrollo generado por Eureka
server:
  port: 8011
message: "hola mundo!!"
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://serveo.net:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-same-zone-eureka: false

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 3
        #minimumNumberOfCalls: 2
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      item:
        base-config: default
  timelimiter:
    instances:
      item:
        timeout-duration: 1s

management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

info:
  app:
    version: 1.0.0
    name: Microservices HelloWorld
    description: Microservices to test Zipkin

spring:
  application:
    zipkin: http://localhost:9411

