# Puerto de entorno de desarrollo generado por Eureka
spring:
  application:
    name: hystrik-server
  profiles:
    active: dev
server:
  port: 8999
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

hystrix:
  dashboard:
    proxy-stream-allow-list: "*"